name: ScheduleCI

on:
  schedule:
    - cron:  '30 4 23 1 *'

jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: Echo Shell Script
        run: ./echo.sh
      - name: Start ScheduleCI
        run: |
            curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"text":"START!"}' \
            ${{ secrets.WEBHOOK_URL }}
      - name: Run TRAP
        run: ./trap.sh