name: ScheduleCI

on: 
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Echo Shell Script
        run: ./echo.sh
      - name: Start ScheduleCI
        run: |
            curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"text":"START!"}' \
            ${{ secrets.WEBHOOK_URL }}
      - name: Run TRAP
        env:
          GITHUB_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: ./trap.sh