name: ScheduleCI

on:
  schedule:
    - cron:  '47 1 23 1 *'
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: Slack Post 
        run: curl -s -X POST -H Content-Type: application/json -d {"text":"hello!"} ${{ secrets.WEBHOOK_URL }}
