name: ScheduleCI

on:
  schedule:
    - cron:  '5 13 22 1 *'
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
        run: echo Doing Something...
